// NOTICE: FILE SHOULDN'T BE DELETED
// routers listed below is auto generated by parsing controller files
// and all configurations will effect http routers

package router

import "github.com/nvwa-io/wago"

func init() {

    wago.CommentRouters["controller/home/Example2Controller"] = append(wago.CommentRouters["controller/home/Example2Controller"], wago.CommentRouter{
		Method:     "HelloWorld",
		Router:     "/example2/hello",
		HTTPMethod: []string{"GET","POST","PUT"},
	})

    wago.CommentRouters["controller/home/Example2Controller"] = append(wago.CommentRouters["controller/home/Example2Controller"], wago.CommentRouter{
		Method:     "HelloWorld2",
		Router:     "/example2/hello/world",
		HTTPMethod: []string{"GET","POST"},
	})

    wago.CommentRouters["controller/ExampleController"] = append(wago.CommentRouters["controller/ExampleController"], wago.CommentRouter{
		Method:     "HelloWorld",
		Router:     "/example/hello",
		HTTPMethod: []string{"GET","POST","PUT"},
	})

    wago.CommentRouters["controller/ExampleController"] = append(wago.CommentRouters["controller/ExampleController"], wago.CommentRouter{
		Method:     "HelloWorld2",
		Router:     "/example/hello/world",
		HTTPMethod: []string{"GET","POST"},
	})

}